If the project key and project name are defined in a properties file … (#1)
* If the project key and project name are defined in a properties file use them, or fall back to the repo name

* Test with upload step

* Upload the SARIF file as an artifact

* Add debug step

* Dont' wait for the quality gate

diff --git a/.github/workflows/sonarqube-scan.yaml b/.github/workflows/sonarqube-scan.yaml
--- a/.github/workflows/sonarqube-scan.yaml
+++ b/.github/workflows/sonarqube-scan.yaml
@@ -25,6 +25,22 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Build SonarQube arguments
+        id: build_args
+        run: |
+          EXTRA_ARGS=""
+          # Check if 'sonar.projectKey' is already defined in the properties file.
+          if ! grep -q "sonar.projectKey" sonar-project.properties; then
+            echo "sonar.projectKey not found in properties file. Using repo name as fallback."
+            EXTRA_ARGS="${EXTRA_ARGS} -Dsonar.projectKey=${{ github.event.repository.name }}"
+          fi
+          # Check if 'sonar.projectName' is already defined in the properties file.
+          if ! grep -q "sonar.projectName" sonar-project.properties; then
+            echo "sonar.projectName not found in properties file. Using repo name as fallback."
+            EXTRA_ARGS="${EXTRA_ARGS} -Dsonar.projectName=${{ github.event.repository.name }}"
+          fi
+          echo "sonar-args=$EXTRA_ARGS" >> "$GITHUB_OUTPUT"
+
       - id: sonar-scan
         uses: sonarsource/sonarqube-scan-action@v4
         env:
@@ -34,10 +50,9 @@ jobs:
           DEBUG2: ${{ github.event.repository.name }}
         with:
           args: >
-            -Dsonar.projectKey=${{ github.event.repository.name }}
-            -Dsonar.projectName=${{ github.event.repository.name }}
+            ${{ steps.build_args.outputs.sonar-args }}
             -Dsonar.sources=.
-            -Dsonar.qualitygate.wait=true
+            -Dsonar.qualitygate.wait=false
             -Dsonar.sarif.path=sonar-report.sarif
             -Dsonar.terraform.provider.aws.version=5.0
             -Dsonar.scm.provider=git
